import XCTest
@testable import KaleidoEngine

// Decoders for Fixtures/golden.json, which is generated by running the REAL web
// serializer (ios/tools/gen-engine-fixtures.ts against src/shared/vector.ts).
//
// The `drawing` in each fixture is decoded from the JSON number literals, so the
// Doubles here are bit-identical to the ones the web serializer was handed — a
// lossy re-encoding in between would make a byte mismatch unattributable.

struct Golden: Decodable {
    let v1: [V1Fixture]
    let v2: [V2Fixture]
    let smooth: SmoothGolden
    /// Layer-duplicate names, trimmed to the format's limit. Here because both
    /// sides trim by extended grapheme cluster and "both implement UAX #29" is a
    /// claim about two separate implementations (REVIEW.md minor mI7).
    let copyNames: [CopyNameFixture]

    struct CopyNameFixture: Decodable {
        let name: String
        let expected: String
    }

    struct V1Fixture: Decodable {
        let name: String
        let drawing: RawV1
        /// v1 canonical bytes.
        let expected: String
        /// The v2 bytes this upgrades into.
        let upgraded: String
        let forHash: String
        let hash: String
    }

    struct V2Fixture: Decodable {
        let name: String
        let drawing: RawV2
        let expected: String
        let forHash: String
        let hash: String
        /// False for fixtures built to bypass the name validator deliberately.
        let parseable: Bool
        let flattened: String?
        let palette: [String]
        let topSym: RawSym?
        let hashTwinOf: String?
    }

    struct SmoothGolden: Decodable {
        let alpha: Double
        let points: [[Double]]
        let cubics: [RawCubic]
    }

    struct RawCubic: Decodable {
        let i: Int
        let c1x, c1y, c2x, c2y, x, y: Double
    }

    struct RawV1: Decodable {
        let bg: String
        let sym: RawSym
        let strokes: [RawStroke]
    }

    struct RawV2: Decodable {
        let bg: String
        let layers: [RawLayer]
    }

    struct RawLayer: Decodable {
        let id: String
        let name: String
        let visible: Bool
        let opacity: Double
        let sym: RawSym
        let strokes: [RawStroke]
    }

    struct RawSym: Decodable {
        let segments: Int
        let mirror: Bool
    }

    struct RawStroke: Decodable {
        let tool: String
        let color: String
        let size: Double
        let opacity: Double
        let po: Int?
        let sm: Int?
        let pts: [[Double]]
    }
}

extension XCTestCase {
    func loadGolden(file: StaticString = #filePath, line: UInt = #line) throws -> Golden {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "golden", withExtension: "json", subdirectory: "Fixtures"),
            "golden.json missing — run: npx vite-node ios/tools/gen-engine-fixtures.ts",
            file: file, line: line
        )
        return try JSONDecoder().decode(Golden.self, from: try Data(contentsOf: url))
    }

    func loadProdVector(file: StaticString = #filePath, line: UInt = #line) throws -> String {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "prod-vector", withExtension: "json", subdirectory: "Fixtures"),
            "prod-vector.json missing",
            file: file, line: line
        )
        return try String(contentsOf: url, encoding: .utf8)
    }
}

// ---- raw → model ----------------------------------------------------------

func makeStroke(_ s: Golden.RawStroke) throws -> Stroke {
    let tool = try XCTUnwrap(BrushTool(rawValue: s.tool))
    return Stroke(
        tool: tool, color: s.color, size: s.size, opacity: s.opacity,
        po: s.po == 1, sm: s.sm == 1,
        pts: s.pts.map { StrokePoint(x: $0[0], y: $0[1], pressure: $0[2]) }
    )
}

func makeDrawing(_ raw: Golden.RawV1) throws -> Drawing {
    Drawing(
        bg: try XCTUnwrap(Background(rawValue: raw.bg)),
        sym: Symmetry(segments: raw.sym.segments, mirror: raw.sym.mirror),
        strokes: try raw.strokes.map(makeStroke)
    )
}

func makeDrawing(_ raw: Golden.RawV2) throws -> DrawingV2 {
    DrawingV2(
        bg: try XCTUnwrap(Background(rawValue: raw.bg)),
        layers: try raw.layers.map { l in
            Layer(id: l.id, name: l.name, visible: l.visible, opacity: l.opacity,
                  sym: Symmetry(segments: l.sym.segments, mirror: l.sym.mirror),
                  strokes: try l.strokes.map(makeStroke))
        }
    )
}
