import XCTest
@testable import KaleidoEngine

/// The interop proof: the Swift serializer must reproduce the web `serialize`
/// output byte-for-byte. Fixtures in Fixtures/golden.json are generated by
/// running the REAL web serializer (ios/tools/gen-engine-fixtures.ts) — never
/// hand-edited — so this test pins us to the source of truth.
final class SerializeGoldenTests: XCTestCase {
    // The raw (full-precision) drawing as stored in the fixture. Doubles are
    // decoded straight from the JSON literals, so they equal the exact doubles
    // the web serializer received — no lossy re-encoding in between.
    private struct Fixture: Decodable {
        let name: String
        let drawing: RawDrawing
        let expected: String
    }
    private struct RawDrawing: Decodable {
        let bg: String
        let sym: RawSym
        let strokes: [RawStroke]
    }
    private struct RawSym: Decodable {
        let segments: Int
        let mirror: Bool
    }
    private struct RawStroke: Decodable {
        let tool: String
        let color: String
        let size: Double
        let opacity: Double
        let pts: [[Double]]
    }

    private func loadFixtures() throws -> [Fixture] {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "golden", withExtension: "json", subdirectory: "Fixtures"),
            "golden.json missing — run: npx vite-node ios/tools/gen-engine-fixtures.ts"
        )
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode([Fixture].self, from: data)
    }

    private func makeDrawing(_ raw: RawDrawing) throws -> Drawing {
        let bg = try XCTUnwrap(Background(rawValue: raw.bg))
        let strokes = try raw.strokes.map { s -> Stroke in
            let tool = try XCTUnwrap(BrushTool(rawValue: s.tool))
            let pts = s.pts.map { StrokePoint(x: $0[0], y: $0[1], pressure: $0[2]) }
            return Stroke(tool: tool, color: s.color, size: s.size, opacity: s.opacity, pts: pts)
        }
        return Drawing(bg: bg, sym: Symmetry(segments: raw.sym.segments, mirror: raw.sym.mirror), strokes: strokes)
    }

    func testSerializeMatchesWebOutputByteForByte() throws {
        let fixtures = try loadFixtures()
        XCTAssertFalse(fixtures.isEmpty, "no fixtures loaded")
        for f in fixtures {
            let drawing = try makeDrawing(f.drawing)
            let out = serialize(drawing)
            XCTAssertEqual(out, f.expected, "byte mismatch for fixture '\(f.name)'")
        }
    }

    /// deserialize(serialized) → serialize must be a fixed point: parsing the web
    /// output and re-serializing yields the identical bytes (round-trip / remix).
    func testDeserializeThenSerializeIsIdempotent() throws {
        for f in try loadFixtures() {
            let parsed = try deserialize(f.expected)
            let reserialized = serialize(parsed)
            XCTAssertEqual(reserialized, f.expected, "round-trip drift for fixture '\(f.name)'")
        }
    }

    // ---- number formatting edge cases (documented parity with JS) ----

    func testNumberFormattingEdgeCases() {
        // (value, decimals, expected) — mirrors JS round + Number.toString.
        let cases: [(Double, Int, String)] = [
            (10, 2, "10"),          // trailing zeros dropped
            (1, 3, "1"),
            (0.5, 3, "0.5"),        // not "0.500"
            (0.05, 3, "0.05"),      // padded leading zero
            (0.001, 3, "0.001"),
            (2.5, 2, "2.5"),
            (-0.1235, 3, "-0.123"), // half toward +∞
            (0.1235, 3, "0.124"),
            (-0.0001, 3, "0"),      // rounds to zero → never "-0"
            (-2, 3, "-2"),
            (7.125, 2, "7.13"),     // size rounding
            (0.333, 3, "0.333"),
        ]
        for (n, d, want) in cases {
            XCTAssertEqual(VectorFormat.format(n, d), want, "format(\(n), \(d))")
        }
    }
}
