import XCTest
@testable import KaleidoEngine

/// The interop proof: the Swift serializer must reproduce the web output
/// byte-for-byte, in both the v1 and the v2 form, and must derive the same
/// content hash. Fixtures in Fixtures/golden.json are generated by running the
/// REAL web serializer (`ios/tools/gen-engine-fixtures.ts` against
/// `src/shared/vector.ts`) — never hand-edited — so this test pins us to the
/// source of truth rather than to someone's transcription of it.
final class SerializeGoldenTests: XCTestCase {

    // ---- v1 form -----------------------------------------------------------

    func testV1SerializeMatchesWebOutputByteForByte() throws {
        let golden = try loadGolden()
        XCTAssertFalse(golden.v1.isEmpty, "no v1 fixtures loaded")
        for f in golden.v1 {
            XCTAssertEqual(serialize(try makeDrawing(f.drawing)), f.expected,
                           "byte mismatch for v1 fixture '\(f.name)'")
        }
    }

    /// deserialize → serialize must be a fixed point: parsing the web output and
    /// re-serializing yields identical bytes (round-trip / remix).
    func testV1DeserializeThenSerializeIsIdempotent() throws {
        for f in try loadGolden().v1 {
            XCTAssertEqual(serialize(try deserialize(f.expected)), f.expected,
                           "round-trip drift for v1 fixture '\(f.name)'")
        }
    }

    /// Every v1 piece in the live gallery goes through this path the first time a
    /// v2 client opens it. The upgraded bytes are what would then be stored, so
    /// they have to match the web's upgrade exactly or the same piece would carry
    /// two different content hashes depending on which client re-saved it.
    func testV1UpgradesToTheSameV2BytesAsTheWeb() throws {
        for f in try loadGolden().v1 {
            let upgraded = try deserializeV2(f.expected)
            XCTAssertEqual(serialize(upgraded), f.upgraded, "v1→v2 upgrade drift for '\(f.name)'")
            // The upgrade is exactly one visible layer at opacity 1 named
            // "Layer 1" with id "l1" — the shape a fresh drawing starts as.
            XCTAssertEqual(upgraded.layers.count, 1, "'\(f.name)': v1 must upgrade to one layer")
            XCTAssertEqual(upgraded.layers[0].id, "l1")
            XCTAssertEqual(upgraded.layers[0].name, "Layer 1")
            XCTAssertTrue(upgraded.layers[0].visible)
            XCTAssertEqual(upgraded.layers[0].opacity, 1)
        }
    }

    func testV1ProjectionAndContentHashMatchTheWeb() throws {
        for f in try loadGolden().v1 {
            let upgraded = try deserializeV2(f.expected)
            XCTAssertEqual(serializeForHash(upgraded), f.forHash, "hash projection drift for '\(f.name)'")
            XCTAssertEqual(try contentHash(f.expected), f.hash, "content hash drift for '\(f.name)'")
        }
    }

    // ---- v2 form -----------------------------------------------------------

    func testV2SerializeMatchesWebOutputByteForByte() throws {
        let golden = try loadGolden()
        XCTAssertFalse(golden.v2.isEmpty, "no v2 fixtures loaded")
        for f in golden.v2 {
            XCTAssertEqual(serialize(try makeDrawing(f.drawing)), f.expected,
                           "byte mismatch for v2 fixture '\(f.name)'")
        }
    }

    func testV2HashProjectionMatchesWebByteForByte() throws {
        for f in try loadGolden().v2 {
            XCTAssertEqual(serializeForHash(try makeDrawing(f.drawing)), f.forHash,
                           "hash projection drift for v2 fixture '\(f.name)'")
        }
    }

    /// Two assertions, deliberately separate: the digest of the projection, and
    /// the whole `contentHash(json)` path. A projection-only check would pass with
    /// a broken parser; a hash-only check would not say which byte moved.
    func testV2ContentHashMatchesWeb() throws {
        for f in try loadGolden().v2 {
            XCTAssertEqual(sha256Hex(f.forHash), f.hash, "digest drift for '\(f.name)'")
            guard f.parseable else { continue }
            XCTAssertEqual(try contentHash(f.expected), f.hash, "contentHash drift for '\(f.name)'")
        }
    }

    func testV2RoundTripIsByteStable() throws {
        for f in try loadGolden().v2 where f.parseable {
            XCTAssertEqual(serialize(try deserializeV2(f.expected)), f.expected,
                           "round-trip drift for v2 fixture '\(f.name)'")
        }
    }

    /// `flattenToV1` is what lets a v2 piece still be served to a v1 client. Both
    /// outcomes matter: the exact bytes when it flattens, and nil when it must
    /// not — a wrong nil breaks old clients, a wrong flatten shows them a
    /// different picture than the one on disk.
    func testV2FlattenToV1MatchesWeb() throws {
        for f in try loadGolden().v2 {
            let flat = flattenToV1(try makeDrawing(f.drawing))
            if let expected = f.flattened {
                XCTAssertEqual(flat.map(serialize), expected, "flatten drift for '\(f.name)'")
            } else {
                XCTAssertNil(flat, "'\(f.name)' must have no v1 form")
            }
        }
    }

    func testV2PaletteAndTopSymMatchWeb() throws {
        for f in try loadGolden().v2 {
            let d = try makeDrawing(f.drawing)
            XCTAssertEqual(paletteOf(d), f.palette, "palette drift for '\(f.name)'")
            if let want = f.topSym {
                XCTAssertEqual(topSym(d), Symmetry(segments: want.segments, mirror: want.mirror),
                               "topSym drift for '\(f.name)'")
            } else {
                XCTAssertNil(topSym(d), "'\(f.name)' must report mixed symmetry as nil")
            }
        }
    }

    /// The projection drops layer ids, layer names and hidden layers. A single
    /// fixture's hash proves none of that; a PAIR that serializes to different
    /// bytes and hashes the same proves all three at once.
    func testHashTwinsHashAlikeButSerializeDifferently() throws {
        let golden = try loadGolden()
        var checked = 0
        for f in golden.v2 {
            guard let twinName = f.hashTwinOf else { continue }
            let twin = try XCTUnwrap(golden.v2.first { $0.name == twinName },
                                     "'\(f.name)' names a missing twin '\(twinName)'")
            let a = try makeDrawing(f.drawing)
            let b = try makeDrawing(twin.drawing)
            XCTAssertNotEqual(serialize(a), serialize(b),
                              "'\(f.name)' and its twin are byte-identical, so they prove nothing")
            XCTAssertEqual(sha256Hex(serializeForHash(a)), sha256Hex(serializeForHash(b)),
                           "'\(f.name)' and twin '\(twinName)' must hash alike")
            checked += 1
        }
        XCTAssertGreaterThan(checked, 0, "golden.json declares no hash twins")
    }

    // ---- real production data ---------------------------------------------

    /// A REAL piece created + serialized by the web app (fetched from production).
    /// Deserializing it and re-serializing in Swift must reproduce the exact same
    /// bytes — proving web→iOS interop on genuine data, not just synthetic cases.
    func testRealProductionVectorRoundTripsByteForByte() throws {
        let original = try loadProdVector()
        XCTAssertEqual(serialize(try deserialize(original)), original,
                       "real production vector did not round-trip byte-for-byte")
    }

    /// The v2 migration applied to real stored data: upgrade it, and flatten it
    /// back. The flattened bytes must equal the stored bytes exactly — that is the
    /// concrete claim that shipping v2 does not disturb anything in the gallery.
    func testRealProductionVectorUpgradesAndReflattensIdentically() throws {
        let original = try loadProdVector()
        let upgraded = try deserializeV2(original)
        XCTAssertEqual(upgraded.layers.count, 1)
        XCTAssertEqual(upgraded.layers[0].id, "l1")
        let flat = try XCTUnwrap(flattenToV1(upgraded), "a v1 piece must always flatten back")
        XCTAssertEqual(serialize(flat), original, "upgrade → flatten was not byte-identical")
        // And the round trip is stable in the v2 form too, so re-saving from a v2
        // client twice does not keep producing new bytes (and new hashes).
        XCTAssertEqual(serialize(try deserializeV2(serialize(upgraded))), serialize(upgraded))
    }

    // ---- number formatting edge cases (documented parity with JS) ----

    func testNumberFormattingEdgeCases() {
        // (value, decimals, expected) — mirrors JS round + Number.toString.
        let cases: [(Double, Int, String)] = [
            (10, 2, "10"),          // trailing zeros dropped
            (1, 3, "1"),
            (0.5, 3, "0.5"),        // not "0.500"
            (0.05, 3, "0.05"),      // padded leading zero
            (0.001, 3, "0.001"),
            (2.5, 2, "2.5"),
            (-0.1235, 3, "-0.123"), // half toward +∞
            (0.1235, 3, "0.124"),
            (-0.0001, 3, "0"),      // rounds to zero → never "-0"
            (-2, 3, "-2"),
            (7.125, 2, "7.13"),     // size rounding
            (0.333, 3, "0.333"),
            (0.0005, 3, "0.001"),   // layer opacity: rounds up, no "0.0005"
            (0, 3, "0"),
        ]
        for (n, d, want) in cases {
            XCTAssertEqual(VectorFormat.format(n, d), want, "format(\(n), \(d))")
        }
    }
}
